### PR TITLE
replace existing icons

### PR DESCRIPTION
**Pull request by freeman212**
- blue background colour taken from the official Vimeo logo
- replaced the like-thumb with the typical Vimeo favourite-heart
- removed dislikes icon, because support is missing (maybe also remove the livestream logo?)

### CODE REVIEW

**Comment by bromix** [comment]
I think we can remove the livestream...I don't think vimeo has support for that. Also do we have a nicer updated Logo (and maybe background)? So the addon will look and shine like new :)
And thanks! :+1:

**Comment by freeman212** [comment]
you mean this icon: https://github.com/bromix/plugin.video.bromix.vimeo/blob/v4.0.1-a1/icon.png ?
btw the fanart is kind of brand-new ;-) I added it to the existing Vimeo addon only a couple of days ago.

**Comment by bromix** [comment]
Ohh...sorry :( I didn't know and yes...the icon xD

**Comment by freeman212** [comment]
I think you could just use the official logo: https://github.com/freeman212/plugin.video.bromix.vimeo/blob/v4.0.1-a1/resources/media/explore.png

or this one, but I think it's a too small: https://github.com/freeman212/plugin.video.bromix.vimeo/blob/v4.0.1-a1/resources/media/vimeo.png

**Comment by bromix** [comment]
thx :)

**Comment by bromix** [comment]
I found this one...I like the gradient:
http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Vimeo.svg/2000px-Vimeo.svg.png

It would be a nice mixture of your suggestion:
https://github.com/freeman212/plugin.video.bromix.vimeo/blob/v4.0.1-a1/resources/media/explore.png

**Comment by bromix** [comment]
I tried something :)


https://github.com/bromix/plugin.video.bromix.vimeo/blob/v4.0.1-a2/icon.png

**Comment by freeman212** [comment]
that looks pretty nice indeed! :)

**Pull request merged**
